
# bundle exec jekyll serve

title: Christian Beth
email: contact@christianbeth.com
description: "PhD candidate in Computer Science at Kiel University, researching semantics-aware knowledge discovery from heterogeneous information networks."  
meta_description: "Your longer or differently worded description for search engines."
tagline: "PhD Candidate in Computer Science · Kiel University"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://christianbeth.com"
github_username:  c-beth
linkedin_username: christian-beth
google_scholar: g991gX4AAAAJ
orcid: 0000-0003-3313-0752
dblp: 299/8629
researchgate: "https://www.researchgate.net/profile/Christian-Beth"

og_image: /assets/cbe.jpg

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

